### PR TITLE
Adding_some_spanish_radios

### PR DESCRIPTION
**Pull request by Brumi-2021**
Hi Stefan ,  thanks for repairing  the previous broken links and the VLC blocked  (user agent issue)  .
Now from  my vscode , playing RUN , it works flawesly . ,
image

 but I do not know why , it does not work from my external terminal ???

image

In this PR , let me add some spanish radios .

Cheers,

### CODE REVIEW

**Comment by stefantalpalaru** [comment]
> it does not work from my external terminal

`emerge PyQt5`

**Comment by stefantalpalaru** [comment]
Thank you for the Spanish radio stations.

I implemented tabs, now that we have three different categories.

**Comment by Brumi-2021** [comment]
Thanks a lot , great job with taps ! 

I am still struggling with the direct command launchment .  From direct terminal It is still not working .
(just working perfectly inside vscode ) . 

The error is that one , 
./radio.py
Traceback (most recent call last):
  File "/opt/bbc_radio-stefan/./radio.py", line 5, in <module>
    from PyQt5.QtCore import QTimer
ModuleNotFoundError: No module named 'PyQt5'


I already have installed both  PyQt5 and PyQt6 , 
image

But it is true that when checking ,  /usr/lib/python3.12/site-packages/PyQt5/bindings/,   I do not see  QTimer ????

image

-------------------------------------------------------
When I am inside vscode , If I write that different line , I got also errors with Qtimer , 

from PyQt5 import QtCore, QtGui, QtWidgets,Qtimer 
ImportError: cannot import name 'Qtimer' from 'PyQt5' (/usr/lib/python3.12/site-packages/PyQt5/__init__.py)

If I test with QTimer , similar , 
ImportError: cannot import name 'QTimer' from 'PyQt5' (/usr/lib/python3.12/site-packages/PyQt5/__init__.py)

I will keep googling and looking for the solution,  but any clue or hint will be welcome , 
Thanks,

**Comment by stefantalpalaru** [comment]
You need "python3_12" added to your "PYTHON_TARGETS" in "/etc/portage/make.conf".

You can see which USE flags were enabled for the installed version in the output of `eix -se PyQt5`.

**Comment by Brumi-2021** [comment]
Hi , initially , I had that condition and not working .  (I do not understand that (fallback , meaning ) . 

eselect python list
Available Python interpreters, in order of preference:    (then I guess it was selected the 3.11 !!!!! ) 
  [1]   python3.11
  [2]   python3.10
  [3]   python3.12 (fallback)

Checking USE flag,  seems installed with PYTHON_TARGETS="python3_12
image

Normally I used different command ,  this , 
image

Anyway , in  in "/etc/portage/make.conf". I do not have that line .
But I tried to send 

sudo eselect python set 3 , and now , I guess that the PYTHON interpreter activated is [1]
image


And it works !!!!!!! 
I thought that the system usually was activating the latest Python version , same as Kernel list , but it seems , not...

Great , eureka !!!  Now  it works ,  thanks again , !!!!
image

**Pull request merged**
